-- Generated by psc-make version 0.6.4
module Context where
import Prim ()
import Prelude ()
import Control.Monad.Eff ()
foreign import data Context :: *
foreign import getContext :: forall e. Control.Monad.Eff.Eff e Context.Context
