-- Generated by psc-make version 0.6.4
module Pixi.Internal where
import Prim ()
import Prelude ()
import Data.Foreign.OOFFI ()
import Control.Monad.Eff ()
foreign import data PixiConversion :: !
foreign import data PIXI :: *
newtype Y = Y Prim.Number
newtype X = X Prim.Number
foreign import pixi :: Pixi.Internal.PIXI
foreign import runY :: Pixi.Internal.Y -> Prim.Number
foreign import runX :: Pixi.Internal.X -> Prim.Number
